name: Lime – An Open Source Text Editor
markdown: redcarpet
pygments: true
exclude: ['Rakefile', 'Gemfile', 'Gemfile.lock']

nav:
  - text: Blog
    url: /blog.html
  - text: Contributing
    url: /contribute.html
  - text: Wiki
    url: https://github.com/limetext/lime/wiki